import Head from 'next/head';
import styled from 'styled-components';
import { Colors, Devices } from '../lib/Theme';
import Hero from './Home/Hero';

const Wrapper = styled.article`
  height: 100vh;
  width: 100%;
  color: ${Colors.White};
  display: flex;
  justify-content: center;

  padding: 0 2rem;

  @media ${Devices.Laptop} {
    padding: 0 1rem;
  }
`;

export default function Home() {
  return (
    <Wrapper>
      <Head>
        <title>Crypto.com NFT Marketplace</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
    </Wrapper>
  );
}
