import Head from 'next/head';
import styled from 'styled-components';
import { Colors, Devices } from '../lib/Theme';
import Carousel from './Home/Carousel';
import Hero from './Home/Hero';
import NewsLetter from './Home/NewsLetter';
import TopCollectibles from './Home/TopCollectibles';

const Wrapper = styled.article`
  color: ${Colors.White};
`;

export default function Home() {
  return (
    <Wrapper>
      <Head>
        <title>Crypto.com NFT Marketplace</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <NewsLetter />
      <Carousel />
      <TopCollectibles />
    </Wrapper>
  );
}
